### ISSUE TITLE
IWLayer V not updated from initialisation at 0

### ISSUE THREAD

**Issue by JohnReid** [LaurenceA/bayesfunc#1]
Hi, thanks for sharing this code. It is very interesting.

I was playing around with the DKP example in `simple.ipynb`. It does indeed fit the data well. However on inspection of the `IWLayer`'s `V` parameter, it was 0 everywhere (its initialised value).

I tried initialising `V` randomly and it creates a qualitatively different fit to the data with a lower ELBO.

I'm guessing the initialisation to all zeros doesn't permit the symmetry to be broken during training and `V` stays 0. However I wasn't sure why the ELBO was worse when initialised randomly. Can you shed any light on this?

**Comment by LaurenceA** [comment]
Thanks: great catch!

We have updated the code here, so it should now be working.  Note that in these simple examples, the optimal V is actually zero (i.e. the underlying GP is good enough) so we usually slightly worse performance now that V is non-zero.

We reran the UCI experiments in the paper, and all of them got better --- sometimes by quite a bit.  Are you happy to be acknowledged on in the final paper?

**Comment by JohnReid** [comment]
I'm glad it was helpful. I would be very happy to be acknowledged. Thanks for that.

One other quick question: are you going to release the scripts for the UCI experiments? It would be nice to see DKPs working on more complex data.

**Comment by JohnReid** [comment]
I have a multiclass classification problem that I would like to try DKPs on. Is there a suitable likelihood in BayesFunc? I think UCI has such data sets so I'm hoping the answer is yes.

**Comment by LaurenceA** [comment]
Likelihoods are all user-specified.  If you look in:

https://github.com/LaurenceA/bayesfunc/blob/master/examples/simple.ipynb

the Normal likelihood is just coming from the PyTorch distribributions
library (but even that isn't necessary, you just need to include the
log-likelihood, however specified into the objective).

**Comment by JohnReid** [comment]
Thanks for the tip on the likelihood.

I wrote a [script](https://github.com/JohnReid/bayesfunc/blob/master/examples/dkp-wine) to predict on the UCI wine data. I just wanted to check if I got the architecture the same as the paper:
```python
# Define network
inducing_batch = 37
net = nn.Sequential(
    bf.FeaturesToKernel(inducing_batch=inducing_batch),
    bf.ReluKernelGram(),
    bf.IWLayer(inducing_batch),
    bf.ReluKernelGram(),
    bf.IWLayer(inducing_batch),
    bf.ReluKernelGram(),
    bf.GIGP(out_features=nclasses, inducing_batch=inducing_batch)
)
net = bf.InducingWrapper(net, inducing_batch=inducing_batch, inducing_shape=(inducing_batch, X.shape[-1]))
```

and I think this is right for the likelihood:
```python
def calculate_elbo(net, samples):
    logits, logpq, _ = bf.propagate(net, X_train.expand(samples, -1, -1))
    loglik = Categorical(logits=logits).log_prob(y_train).sum(-1)
    assert loglik.shape == (samples,)
    assert logpq.shape == (samples,)
    return loglik + logpq / X_train.shape[0]
```

**Comment by sebastianober** [comment]
Hi John, sorry for the slow reply, we only just realized that we hadn't gotten back to you.

The network you've written should work, but what we actually did was

```
inducing_data, inducing_targets = next(iter(uci.trainloader))
inducing_data = inducing_data[:inducing_batch]
inducing_targets = inducing_targets[:inducing_batch]

def diwp_layer():
    return nn.Sequential(bnn.IWLayer(inducing_batch), bnn.ReluKernelGram())
net = nn.Sequential(
    bnn.Bias(in_features),
    bnn.MultFeatures(in_features),
    bnn.ReluKernelFeatures(inducing_batch),
    *[diwp_layer() for _ in range(args.depth-1)],
    bnn.GIGP(out_features=1, inducing_targets=inducing_targets, inducing_batch=inducing_batch, log_prec_init=0.)
)
net = bnn.InducingWrapper(net, inducing_batch, inducing_data=inducing_data)
net = nn.Sequential(net, bnn.MultFeatures(), bnn.NormalLearnedScale())
```

The `bnn.NormedLearnedScale()` at the output basically encodes the Gaussian likelihood, returning a Torch normal distribution with appropriate loc and scale. This means that we can compute the ELBO as

```
for data, target in trainloader:    # minibatching
    data = data.expand(train_samples, *data.shape)
    Pf, logPQw, _ = bf.propagate(net, data)

    assert target.shape == output.loc.shape[1:]

    ll = Pf.log_prob(target.unsqueeze(0)).mean(0).sum()
    elbo = ll + logPQw.mean()*target.shape[0]/lenX  # scaling for minibatches
```

I hope this helps, and we're happy to answer any more questions (apologies again for the delay). We still need to do some work on our end to document everything a bit better.

**Comment by sebastianober** [comment]
This should be resolved now.
